//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminYonetim.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMenu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblMenu()
        {
            this.TblPage = new HashSet<TblPage>();
        }
    
        public int ID { get; set; }
        public string Adi { get; set; }
        public int KonumID { get; set; }
        public string KonumTipi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblPage> TblPage { get; set; }
    }
}
