//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminYonetim.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblPage
    {
        public int ID { get; set; }
        public string Baslik { get; set; }
        public string Icerik { get; set; }
        public int MenuID { get; set; }
        public string MetaDescription { get; set; }
        public string MetaKeyword { get; set; }
        public int BannerID { get; set; }
    
        public virtual TblMenu TblMenu { get; set; }
    }
}
